export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const GET_CLOSED_DATES = 'GET_CLOSED_DATES';
export const GET_CLOSED_DATES_PENDING = 'GET_CLOSED_DATES_PENDING';
export const GET_CLOSED_DATES_FULFILLED = 'GET_CLOSED_DATES_FULFILLED';
export const GET_CLOSED_DATES_REJECTED = 'GET_CLOSED_DATES_REJECTED';

export const GET_RESTAURANT_SETUP = 'GET_RESTAURANT_SETUP';
export const GET_RESTAURANT_SETUP_PENDING = 'GET_RESTAURANT_SETUP_PENDING';
export const GET_RESTAURANT_SETUP_FULFILLED = 'GET_RESTAURANT_SETUP_FULFILLED';
export const GET_RESTAURANT_SETUP_REJECTED = 'GET_RESTAURANT_SETUP_REJECTED';