export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const GET_CLOSED_DATES = 'GET_CLOSED_DATES';
export const GET_CLOSED_DATES_PENDING = 'GET_CLOSED_DATES_PENDING';
export const GET_CLOSED_DATES_FULFILLED = 'GET_CLOSED_DATES_FULFILLED';
export const GET_CLOSED_DATES_REJECTED = 'GET_CLOSED_DATES_REJECTED';

export const GET_RESTAURANT_SETUP = 'GET_RESTAURANT_SETUP';
export const GET_RESTAURANT_SETUP_PENDING = 'GET_RESTAURANT_SETUP_PENDING';
export const GET_RESTAURANT_SETUP_FULFILLED = 'GET_RESTAURANT_SETUP_FULFILLED';
export const GET_RESTAURANT_SETUP_REJECTED = 'GET_RESTAURANT_SETUP_REJECTED';

export const GET_CUSTOMER_CODES = 'GET_CUSTOMER_CODES';
export const GET_CUSTOMER_CODES_PENDING = 'GET_CUSTOMER_CODES_PENDING';
export const GET_CUSTOMER_CODES_FULFILLED = 'GET_CUSTOMER_CODES_FULFILLED';
export const GET_CUSTOMER_CODES_REJECTED = 'GET_CUSTOMER_CODES_REJECTED';

export const GET_AVAILABILITY = 'GET_AVAILABILITY';
export const GET_AVAILABILITY_PENDING = 'GET_AVAILABILITY_PENDING';
export const GET_AVAILABILITY_FULFILLED = 'GET_AVAILABILITY_FULFILLED';
export const GET_AVAILABILITY_REJECTED = 'GET_AVAILABILITY_REJECTED';

export const SET_TIMESLOT = 'SET_TIMESLOT';

export const SET_TERMS = 'SET_TERMS';

export const SET_INITIAL_FORM_STATE = 'SET_INITIAL_FORM_STATE';
export const RESET_INITIAL_FORM_STATE = 'RESET_INITIAL_FORM_STATE';

export const PAGE_NUMBER = 'PAGE_NUMBER';

export const RESET_AVAILABILITY = 'RESET_AVAILABILITY';

export const RESET_TIMESLOT = 'RESET_TIMESLOT';

export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING';
export const CREATE_BOOKING_FULFILLED = 'CREATE_BOOKING_FULFILLED';
export const CREATE_BOOKING_REJECTED = 'CREATE_BOOKING_REJECTED';
export const CREATE_BOOKING_PAYMENT_VALID = 'CREATE_BOOKING_PAYMENT_VALID';
export const CREATE_BOOKING_STRIPE_TOKEN = 'CREATE_BOOKING_STRIPE_TOKEN';
export const CREATE_BOOKING_STRIPE_TOKEN_PENDING = 'CREATE_BOOKING_STRIPE_TOKEN_PENDING';
export const CREATE_BOOKING_STRIPE_TOKEN_FULFILLED = 'CREATE_BOOKING_STRIPE_TOKEN_FULFILLED';
export const CREATE_BOOKING_STRIPE_TOKEN_REJECTED = 'CREATE_BOOKING_STRIPE_TOKEN_REJECTED';

export const GET_BOOKING = 'GET_BOOKING';
export const GET_BOOKING_PENDING = 'GET_BOOKING_PENDING';
export const GET_BOOKING_FULFILLED = 'GET_BOOKING_FULFILLED';
export const GET_BOOKING_REJECTED = 'GET_BOOKING_REJECTED';

export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const UPDATE_BOOKING_FULFILLED = 'UPDATE_BOOKING_FULFILLED';
export const UPDATE_BOOKING_PENDING = 'UPDATE_BOOKING_PENDING';
export const UPDATE_BOOKING_REJECTED = 'UPDATE_BOOKING_REJECTED';

export const CONFIRM_BOOKING = 'CONFIRM_BOOKING';
export const CONFIRM_BOOKING_FULFILLED = 'CONFIRM_BOOKING_FULFILLED';
export const CONFIRM_BOOKING_PENDING = 'CONFIRM_BOOKING_PENDING';
export const CONFIRM_BOOKING_REJECTED = 'CONFIRM_BOOKING_REJECTED';

export const SET_AMEND_BOOKING = 'SET_AMEND_BOOKING';
export const CHANGE_DATE_CLICKED = 'CHANGE_DATE_CLICKED';
