export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const GET_CLOSED_DATES = 'GET_CLOSED_DATES';
export const GET_CLOSED_DATES_PENDING = 'GET_CLOSED_DATES_PENDING';
export const GET_CLOSED_DATES_FULFILLED = 'GET_CLOSED_DATES_FULFILLED';
export const GET_CLOSED_DATES_REJECTED = 'GET_CLOSED_DATES_REJECTED';

export const GET_RESTAURANT_SETUP = 'GET_RESTAURANT_SETUP';
export const GET_RESTAURANT_SETUP_PENDING = 'GET_RESTAURANT_SETUP_PENDING';
export const GET_RESTAURANT_SETUP_FULFILLED = 'GET_RESTAURANT_SETUP_FULFILLED';
export const GET_RESTAURANT_SETUP_REJECTED = 'GET_RESTAURANT_SETUP_REJECTED';

export const GET_AVAILABILITY = 'GET_AVAILABILITY';
export const GET_AVAILABILITY_PENDING = 'GET_AVAILABILITY_PENDING';
export const GET_AVAILABILITY_FULFILLED = 'GET_AVAILABILITY_FULFILLED';
export const GET_AVAILABILITY_REJECTED = 'GET_AVAILABILITY_REJECTED';